# Copyright (c) 2023 [Ribose Inc](https://www.ribose.com).
# All rights reserved.
# This file is a part of tamatebako
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

name: 'Setup Ubuntu'
description: 'Setup Ubuntu ci environment for tebako'
inputs:
  cache:
    description: 'Tebako cache mode: off/build/use'
    required: true
    type: string
  cache_path:
    description: 'Tebako cache root folder'
    required: true
    default: '.tebako/deps'
    type: string
  ruby_version:
    description: 'Ruby version to install, "env" to use RUBY_VER environment variable'
    required: true
    default: 'env'
    type: string
  bundler_version:
    description: 'Bundler version to install'
    required: true
    default: 'default'
    type: string
runs:
  using: "composite"
  steps:
    - name: Setup environment
      if: inputs.cache != 'off'
      shell: bash
      run: cat common.env >> $GITHUB_ENV

    - name: Install packages
      shell: bash
      run: |
        sudo apt-get -y update
        sudo apt-get -y install                                                   \
        binutils-dev libevent-dev acl-dev libfmt-dev libjemalloc-dev              \
        libdouble-conversion-dev libiberty-dev liblz4-dev liblzma-dev libssl-dev  \
        libboost-filesystem-dev libboost-program-options-dev libboost-system-dev  \
        libboost-iostreams-dev  libboost-date-time-dev libboost-context-dev       \
        libboost-regex-dev libboost-thread-dev libbrotli-dev libunwind-dev        \
        libdwarf-dev libelf-dev libgoogle-glog-dev libffi-dev libgdbm-dev         \
        libyaml-dev libncurses-dev libreadline-dev libutfcpp-dev

    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby_version != 'env' && inputs.ruby_version || env.RUBY_VER }}
        bundler: ${{ inputs.bundler_version }}
        bundler-cache: false

    - name: Install bundle
      if: inputs.cache != 'off'
      shell: bash
      run: |
        bundle install
        bundle exec rake generate_version_txt

    - name: Create deps folder
      if: inputs.cache != 'off'
      shell: bash
      run: mkdir -p ${{ inputs.cache_path }}

    - name: Process cache
      if: inputs.cache != 'off'
      uses: actions/cache@v3
      with:
        path: ${{ inputs.cache_path }}
        key: ${{ matrix.os }}-${{ env.CC }}-${{ hashFiles('*.env') }}-v${{ env.CACHE_VER }}
        fail-on-cache-miss: inputs.cache == 'use'
