name: lint

on:
  push:
    paths-ignore:
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - .github/workflows/ubuntu.yml
      - .github/workflows/macos.yml
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - .github/workflows/ubuntu.yml
      - .github/workflows/macos.yml
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ludeeus/action-shellcheck@master
        with:
          additional_files: 'tebako'
          ignore_paths: deps
        env:
          SHELLCHECK_OPTS: -x
