# Copyright (c) 2021-2023 [Ribose Inc](https://www.ribose.com).
# All rights reserved.
# This file is a part of tamatebako
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

name: MacOS

on:
  schedule:
    - cron: "0 7 * * 1"
  push:
    branches:  [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - .github/workflows/lint.yml
      - .github/workflows/ubuntu.yml
      - .github/workflows/alpine.yml
      - .github/workflows/windows-msys.yml
      - .cirrus.yml
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - .github/workflows/lint.yml
      - .github/workflows/ubuntu.yml
      - .github/workflows/alpine.yml
      - .github/workflows/windows-msys.yml
      - .cirrus.yml
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

env:
  CC: clang
  CXX: clang++
# Cache version
  CACHE_VER: 33
  VERBOSE: no

jobs:
  setup:
    name: setup ${{ matrix.os }} [CC clang]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11.0 ]
    steps:
      - name: Checkout tebako packaging environment
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup environment
        run: cat common.env >> $GITHUB_ENV

      - name: Select XCode 12.4 & SDK 11.1
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.4'

      - name: Install packages
# Already installed: openssl@1.1, libevent, libsodium, lz4, xz, zlib, gdbm, ncurses
        run: |
          brew install \
          bison flex binutils libffi double-conversion boost jemalloc fmt glog \
          gnu-sed bash pkg-config

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VER }}
          bundler: ${{ env.BUNDLER_VER }}
          bundler-cache: false

      - name: Create deps folder
        run: mkdir ${{ github.workspace }}/${{ env.DEPS }}

      - name: Process cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/${{ env.DEPS }}
          key: ${{ matrix.os }}-${{ env.CC }}-${{ hashFiles('**/common.env') }}-v${{ env.CACHE_VER }}

      - name: tebako setup
        run: |
          bundle install
          bundle exec rake generate_version_txt
          ${{ github.workspace }}/exe/tebako setup

  tests-1:
    needs: setup
    name: tests-1 ${{ matrix.os }} Ruby ${{ matrix.package_ruby_ver }} CC clang
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11.0 ]
        package_ruby_ver: [ '3.0.6' ]
    steps:
      - name: Checkout tebako packaging environment
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup environment
        run: cat common.env >> $GITHUB_ENV

      - name: Select XCode 12.4 & SDK 11.1
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.4'

      - name: Install packages
# Already installed: openssl@1.1, libevent, libsodium, lz4, xz, zlib, gdbm, ncurses
        run: |
          brew install \
          bison flex binutils libffi double-conversion boost jemalloc fmt glog \
          gnu-sed bash pkg-config

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VER }}
          bundler: ${{ env.BUNDLER_VER }}
          bundler-cache: false

      - name: Create deps folder
        run: mkdir ${{ github.workspace }}/${{ env.DEPS }}

      - name: Process cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/${{ env.DEPS }}
          key: ${{ matrix.os }}-${{ env.CC }}-${{ hashFiles('**/common.env') }}-v${{ env.CACHE_VER }}

      - name: Cache check
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "Failed to upload cache"
          false

      - name: Checkout shell test framework
        uses: actions/checkout@v3
        with:
          repository: kward/shunit2
          path: ${{github.workspace}}/tests/shunit2
          fetch-depth: 1

      - name: Run tebako tests (set no. 1)
        run:  |
          bundle install
          RUBY_VER=${{ matrix.package_ruby_ver }} ${{github.workspace}}/tests/scripts/functional-tests.sh

      - name: Upload tebako test packages
        if: ${{ matrix.package_ruby_ver == env.RUBY_VER }}
        uses: actions/upload-artifact@v3
        with:
          name: test-packages
          retention-days: 1
          path: |
            test-01-package
            test-11-package
            test-15-package
            test-18-package
            test-19-package

  tests-2:
    needs: setup
    name: tests-2 ${{ matrix.os }} Ruby ${{ matrix.package_ruby_ver }} CC clang
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11.0 ]
        package_ruby_ver: [ '2.7.7', '3.0.6', '3.1.4' ]
    steps:
      - name: Checkout tebako packaging environment
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup environment
        run: cat common.env >> $GITHUB_ENV

      - name: Select XCode 12.4 & SDK 11.1
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.4'

      - name: Install packages
# Already installed: openssl@1.1, libevent, libsodium, lz4, xz, zlib, gdbm, ncurses
        run: |
          brew install \
          bison flex binutils libffi double-conversion boost jemalloc fmt glog \
          gnu-sed bash pkg-config

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VER }}
          bundler: ${{ env.BUNDLER_VER }}
          bundler-cache: false

      - name: Create deps folder
        run: mkdir ${{ github.workspace }}/${{ env.DEPS }}

      - name: Process cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/${{ env.DEPS }}
          key: ${{ matrix.os }}-${{ env.CC }}-${{ hashFiles('**/common.env') }}-v${{ env.CACHE_VER }}

      - name: Cache check
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "Failed to upload cache"
          false

      - name: Run tebako tests (set no. 2)
        run: |
          bundle install
          RUBY_VER=${{ matrix.package_ruby_ver}} ruby ${{github.workspace}}/tests-2/tebako-test.rb

  test-on-macos-latest:
    needs: tests-1
    runs-on: macos-latest
    steps:
      - name: Checkout tebako packaging environment
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Download test packages
        uses: actions/download-artifact@v3
        with:
          name: test-packages

      - name: Run test packages
        run:  ${{github.workspace}}/tests/scripts/cross-tests.sh
