name: Ubuntu build

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, issue-18 ]
    paths-ignore:
      - 'docs/**'
      - '**.adoc'
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'docs/**'
      - '**.adoc'
      - '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
# Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
# The folder for dwarfs and other dependenies
  DEPS: deps
# GitHub dependencies' 
  INCBIN_TAG:    "348e36b"
  DWARFS_WR_TAG: "16bcac1"
# Tarball dependencies
  RUBY_VER:   "2.7.4"
  RUBY_HASH:  "3043099089608859fc8cce7f9fdccaa1f53a462457e3838ec3b25a7d609fbc5b"
  BUNDLER_VER: "2.2.3"
  BUNDLER_HASH: "6acefda4aeb34cb3d69aff06affce10424d69f484402a9f7f5577e8c698070db"

jobs:
  Ubuntu-build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
    - uses: actions/checkout@v2

    - name: Create deps folder and cache key
      run: |
        mkdir ${{github.workspace}}/${{env.DEPS}}
        echo "Keys" > key.txt
        echo  ${{ env.INCBIN_TAG }} >> key.txt
        echo  ${{ env.DWARFS_WR_TAG }} >> key.txt
        echo  ${{ env.RUBY_HASH }} >> key.txt
        echo  ${{ env.BUNDLER_HASH }} >> key.txt

    - name: Clone shell test framework
      run: git clone https://github.com/kward/shunit2.git ${{github.workspace}}/tests/shunit2 --depth 1
      
    - name: Process cache
      uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/${{env.DEPS}}
        key: ${{ github.workflow }}-${{ hashFiles('key.txt') }}-v17

# Ref CMakeLists.txt for comments
    - name: Install packages Ubuntu
      run: |
        sudo apt-get update
        sudo apt-get install \
        ronn binutils-dev libarchive-dev libevent-dev libjemalloc-dev acl-dev libxml2-dev \
        libdouble-conversion-dev libiberty-dev liblz4-dev liblzma-dev libssl-dev \
        libboost-context-dev libboost-filesystem-dev libboost-program-options-dev \
        libboost-regex-dev libboost-system-dev libboost-thread-dev \
        libunwind-dev libdwarf-dev libelf-dev libfmt-dev libfuse3-dev libgoogle-glog-dev \
        libffi-dev libgdbm-dev libyaml-dev libncurses-dev libreadline-dev libsqlite3-dev
        

# Tests
#  00. Very basic tebako CLI tests (error handling)
#  --  tebako setup (baseline for tests 01-17)
#  01. Simple Ruby script, relative path to entry point  
#  02. Simple Ruby script, relative path to entry point, non exisitng entrance      Expected error at configure step
#  03. Simple Ruby script, absolute path to entry point 
#  04. Simple Ruby script, absolute path to entry point, relative path to root      
#  05. Simple Ruby script, absolute path to entry point, not within root            Expected error at configure step
#  06. Rails project                                                                                                       [TODO]
#  07. Rails project, ruby and bundler version mismatch                             Expected error at build step
#  08. Rails project, no entry point                                                Expected error at build step           [TODO]
#  09. Ruby gem (xxx.gem file)  
#  10. Ruby gem (xxx.gem file), no entry point                                      Expected error at build step
#  11. Ruby gem, no gemfile, with gemspec                                             
#  12. Ruby gem, no gemfile, multiple gemspecs                                      Expected error at configure step
#  13. Ruby gem, no gemfile, gemspec error                                          Expected error at build step  
#  14. Ruby gem, no gemfile, gemspec, no entry point                                Expected error at build step  
#  15. Ruby gem, gemfile, gemspec                                             
#  16. Ruby gem, gemfile, gemspec error                                             Expected error at build step  
#  17. Ruby gem, gemfile, gemspec, no entry point                                   Expected error at build step  
#  18 - 39  -- reserved
#  40. CLI.  Change output name                                                     [depends on Test-01] 
#  41 - 49  reserved
#  50. AUC. Check that it is possible to verify content of package fs               [depends on Test-01] 

    - name: tebako functional tests
      run: ${{github.workspace}}/tests/test-00/test-00.sh verbose

#    - name: Test01 - tebako press - [Simple Ruby script, relative path to entry point]
#      run: | 
#        ${{github.workspace}}/bin/tebako press                   \
#              --root="${{github.workspace}}/tests/test-01"       \
#              --entry-point="test.rb"                              
                                            
#    - name: Test01 - Run packaged solution - [Simple Ruby script, relative path to entry point]
#      run:  ${{github.workspace}}/output/tebako
# [ TODO]        echo Tebako exit code $?

#    - name: Test02 - tebako press - [Simple Ruby script, relative path to entry point, non exisitng entrance]
#      run: | 
#        ${{github.workspace}}/tests/scripts/press_with_failure.sh \
#              "${{github.workspace}}/tests/test-01"               \
#              "test-does-not-exist.rb"                            \
#              103                   
              
#    - name: Test03 - tebako press - [Simple Ruby script, absolute path to entry point]
#      run: | 
#        ${{github.workspace}}/bin/tebako press                   \
#              --root="${{github.workspace}}/tests/test-01"       \
#              --entry-point="${{github.workspace}}/tests/test-01/test.rb"                              

#    - name: Test03 - Run packaged solution - [Simple Ruby script, absolute path to entry point]
#      run:  ${{github.workspace}}/output/tebako

#    - name: Test04 - tebako press - [Simple Ruby script, absolute path to entry point, relative path to root ]
#      run: | 
#        ${{github.workspace}}/bin/tebako press                   \
#              --root="tests/test-01"                             \
#              --entry-point="test.rb"                              

#    - name: Test04 - Run packaged solution - [Simple Ruby script, absolute path to entry point, relative path to root ]
#      run:  ${{github.workspace}}/output/tebako
                                           
#    - name: Test05 - tebako press - [Simple Ruby script, absolute path to entry point, not within root]
#      run: | 
#        ${{github.workspace}}/tests/scripts/press_with_failure.sh \
#              "${{github.workspace}}/tests/test-01"               \
#              "${{github.workspace}}/tests/test-00/test.rb"       \
#              103                           

#    - name: Test06 - tebako press - [Rails project]
#      run: | 
#        ${{github.workspace}}/bin/tebako press                    \
#              --root="${{github.workspace}}/tests/test-06"        \
#              --entry-point="rails"                              

#    - name: Test06 - Run packaged solution - [Rails project]
#      run:  ${{github.workspace}}/output/tebako

#    - name: Test07 - tebako press - [Rails project, ruby and bundler version mismatch]
#      run: | 
#        ${{github.workspace}}/tests/scripts/press_with_failure.sh \
#              "${{github.workspace}}/tests/test-07"               \
#              "rails"                                             \
#              104   

#    - name: Test08 - tebako press - [Rails project, no entry point]
#      run: | 
#        ${{github.workspace}}/tests/scripts/press_with_failure.sh \
#              "${{github.workspace}}/tests/test-06"               \
#              "test-does-not-exist.rb"                            \
#              104                            

#    - name: Test09 - tebako press - [xxx.gem, no gemspec, no gemfile]
#      run: | 
#        ${{github.workspace}}/bin/tebako press                    \
#              --root="${{github.workspace}}/tests/test-09"        \
#              --entry-point="tebako-test-run.rb"                              

#    - name: Test09 - Run packaged solution - [xxx.gem, no gemspec, no gemfile]
#      run:  ${{github.workspace}}/output/tebako

#    - name: Test10 - tebako press - [xxx.gem, no gemspec, no gemfile, entry point does not exist]
#      run: | 
#        ${{github.workspace}}/tests/scripts/press_with_failure.sh \
#              "${{github.workspace}}/tests/test-09"               \
#              "test-does-not-exist.rb"                            \
#              104                              

#    - name: Test11 - tebako press - [Ruby gem, gemspec, no gemfile]
#      run: | 
#        ${{github.workspace}}/bin/tebako press                    \
#              --root="${{github.workspace}}/tests/test-11"        \
#              --entry-point="tebako-test-run.rb"                              

#    - name: Test11 - Run packaged solution - [Ruby gem, no gemfile]
#      run:  ${{github.workspace}}/output/tebako

#    - name: Test12 - tebako press - [Ruby gem, multiple gemspecs]
#      run: | 
#        ${{github.workspace}}/tests/scripts/press_with_failure.sh \
#              "${{github.workspace}}/tests/test-12"               \
#              "tebako-test-run.rb"                                \
#              103                            

#    - name: Test13 - tebako press - [Ruby gem, no gemfile, gemspec error]
#      run: | 
#        ${{github.workspace}}/tests/scripts/press_with_failure.sh \
#              "${{github.workspace}}/tests/test-13"               \
#              "tebako-test-run.rb"                                \
#              104                      

#    - name: Test14 - tebako press - [Ruby gem, gemspec, no gemfile, entry point does not exist]
#      run: | 
#        ${{github.workspace}}/tests/scripts/press_with_failure.sh \
#              "${{github.workspace}}/tests/test-11"               \
#              "test-does-not-exist.rb"                            \
#              104  

#    - name: Test15 - tebako press - [Ruby gem, gemspec, gemfile]
#      run: | 
#        ${{github.workspace}}/bin/tebako press                   \
#              --root="${{github.workspace}}/tests/test-15"       \
#              --entry-point="tebako-test-run.rb"                              

#    - name: Test15 - Run packaged solution - [Ruby gem, gemspec, gemfile]
#      run:  ${{github.workspace}}/output/tebako

#    - name: Test16 - tebako press - [Ruby gem, gemspec, gemfile with error]
#      run: | 
#        ${{github.workspace}}/tests/scripts/press_with_failure.sh \
#              "${{github.workspace}}/tests/test-16"               \
#              "tebako-test-run.rb"                                \
#              104                   

#    - name: Test17 - tebako press - [Ruby gem, gemspec, gemfile, entry point does not exist]
#      run: | 
#        ${{github.workspace}}/tests/scripts/press_with_failure.sh \
#              "${{github.workspace}}/tests/test-15"               \
#              "test-does-not-exist.rb"                            \
#              104  

#    - name: Test40 - CLI - Change output file name     
#      run: |    
#        ${{github.workspace}}/bin/tebako press                    \
#              --r "${{github.workspace}}/tests/test-01"           \
#              --e "test.rb" -o "tamatebako" 
#        ${{github.workspace}}/output/tamatebako                          
    
#    - name: Test50 -AUC - Check that it is possible to verify content of packaged fs          
#      run: |
#        ${{github.workspace}}/bin/tebako press                    \
#              --root="${{github.workspace}}/tests/test-01"        \
#              --entry-point="test.rb"  
#        deps/bin/dwarfs output/tebako home/tebako                           
