name: Ubuntu build

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master, issue-1 ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
# Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release
# The folder for dwarfs and other dependenies
  DEPS: deps
# Dependencies' tags
  INCBIN_TAG: 348e36b
  DWARFS_TAG: 78401c3
  RUBY_VER:   2.6.3
  RUBY_HASH:  2347ed6ca5490a104ebd5684d2b9b5eefa6cd33c


jobs:
  Ubuntu-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create deps folder
      run: mkdir ${{github.workspace}}/${{env.DEPS}}

    - uses: actions/cache@v2
      with:
        path: ${{github.workspace}}/${{env.DEPS}}
        key: ${{ github.workflow }}-${{env.INCBIN_TAG}}-${{env.DWARFS_TAG}}-${{env.RUBY_HASH}}-v6

    - name: Install packages Ubuntu
# Already installed: bison flex fuse3 pkg-config 
      run: |
        sudo apt-get install \
        ronn binutils-dev libarchive-dev libevent-dev libjemalloc-dev acl-dev libxml2-dev \
        libdouble-conversion-dev libiberty-dev liblz4-dev liblzma-dev libssl-dev \
        libboost-context-dev libboost-filesystem-dev libboost-program-options-dev \
        libboost-regex-dev libboost-system-dev libboost-thread-dev \
        libunwind-dev libdwarf-dev libelf-dev libfmt-dev libfuse3-dev libgoogle-glog-dev 
        
    - name: CMake Configure
      run: | 
        cmake -B ${{github.workspace}}                       \
              -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}         \
              -DDEPS=${{github.workspace}}/${{env.DEPS}}     \
              -DGHA_DWARFS_VERSION=${{env.DWARFS_VERSION}}   \
              -DGHA_DWARFS_CHECKSUM=${{env.DWARFS_CHECKSUM}}
              -DPREFIX=${{github.workspace}}

    - name: Create mount point
      run: |
        sudo mkdir -p /home/tebako 
        sudo chmod a+w /home/tebako
        sudo chmod g+w /home/tebako

    - name: Create mount point
      run: |
        sudo mkdir -p /home/tebako 
        sudo chmod a+w /home/tebako
        sudo chmod g+w /home/tebako

    - name: Run
      run: sudo /usr/local/bin/tebako
