# Copyright (c) 2021-2023 [Ribose Inc](https://www.ribose.com).
# All rights reserved.
# This file is a part of tamatebako
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# ``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDERS OR CONTRIBUTORS
# BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.

name: Ubuntu

on:
  schedule:
    - cron: "0 6 * * 1"
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - .github/workflows/lint.yml
      - .github/workflows/macos.yml
      - .github/workflows/alpine.yml
      - .github/workflows/windows-msys.yml
      - .cirrus.yml
  pull_request:
    paths-ignore:
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - .github/workflows/lint.yml
      - .github/workflows/macos.yml
      - .github/workflows/alpine.yml
      - .github/workflows/windows-msys.yml
      - .cirrus.yml
  workflow_dispatch:

concurrency:
  group: '${{ github.workflow }}-${{ github.job }}-${{ github.head_ref || github.ref_name }}'
  cancel-in-progress: true

env:
  CACHE_VER: 37
  DEBIAN_FRONTEND: "noninteractive"
  TZ: "Etc/UTC"
# show cmake output aka verbose (yes/no)
  VERBOSE: no


jobs:
  setup:
    name: setup ${{ matrix.os }} [CC ${{ matrix.env.CC }}]
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
        env:
          - CC: gcc
            CXX: g++
          - CC: clang
            CXX: clang++
    env: ${{ matrix.env }}
    steps:
      - name: Checkout tebako packaging environment
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup environment
        run: cat common.env >> $GITHUB_ENV

# https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu2004-README.md
# https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md
# Already installed: bison flex pkg-config

# gcc/g++ 9 is also there otherwise we would need:
# sudo add-apt-repository ppa:ubuntu-toolchain-r/test
# sudo apt update
# sudo apt install gcc-9 g++-9

      - name: Switch to gcc-9
        if: ${{ matrix.env.CC == 'gcc' }}
        run: |
          sudo update-alternatives \
            --install /usr/bin/gcc gcc /usr/bin/gcc-9 100 \
            --slave /usr/bin/g++ g++ /usr/bin/g++-9 \
            --slave /usr/bin/gcov gcov /usr/bin/gcov-9
          sudo update-alternatives --set gcc /usr/bin/gcc-9

      - name: Install packages
        run: |
          sudo apt-get -y update
          sudo apt-get -y install \
          binutils-dev libevent-dev acl-dev libfmt-dev libjemalloc-dev \
          libdouble-conversion-dev libiberty-dev liblz4-dev liblzma-dev libssl-dev \
          libboost-context-dev libboost-filesystem-dev libboost-program-options-dev \
          libboost-regex-dev libboost-system-dev libboost-thread-dev \
          libunwind-dev libdwarf-dev libelf-dev libfuse-dev libgoogle-glog-dev \
          libffi-dev libgdbm-dev libyaml-dev libncurses-dev libreadline-dev \
          libsqlite3-dev

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VER }}
          bundler: ${{ env.BUNDLER_VER }}
          bundler-cache: false

      - name: Create deps folder
        run: mkdir ${{ github.workspace }}/${{ env.DEPS }}

      - name: Process cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/${{ env.DEPS }}
          key: ${{ matrix.os }}-${{ env.CC }}-${{ hashFiles('**/common.env') }}-v${{ env.CACHE_VER }}

      - name: tebako setup
        run: |
          bundle install
          ${{ github.workspace }}/exe/tebako setup

  tests-1:
    needs: setup
    name: tests-1 ${{ matrix.os }} Ruby ${{ matrix.package_ruby_ver }} CC ${{ matrix.env.CC }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
        package_ruby_ver: [ '3.0.6' ]
        env:
          - CC: gcc
            CXX: g++
          - CC: clang
            CXX: clang++
    env: ${{ matrix.env }}
    steps:
      - name: Checkout tebako packaging environment
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup environment
        run: cat common.env >> $GITHUB_ENV

      - name: Switch to gcc-9
        if: ${{ matrix.env.CC == 'gcc' }}
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9
          sudo update-alternatives --set gcc /usr/bin/gcc-9

      - name: Install packages
        run: |
          sudo apt-get -y update
          sudo apt-get -y install \
          binutils-dev libevent-dev acl-dev libfmt-dev libjemalloc-dev \
          libdouble-conversion-dev libiberty-dev liblz4-dev liblzma-dev libssl-dev \
          libboost-context-dev libboost-filesystem-dev libboost-program-options-dev \
          libboost-regex-dev libboost-system-dev libboost-thread-dev \
          libunwind-dev libdwarf-dev libelf-dev libfuse-dev libgoogle-glog-dev \
          libffi-dev libgdbm-dev libyaml-dev libncurses-dev libreadline-dev \
          libsqlite3-dev

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VER }}
          bundler: ${{ env.BUNDLER_VER }}
          bundler-cache: false

      - name: Create deps folder
        run: mkdir ${{github.workspace}}/${{env.DEPS}}

      - name: Process cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/${{ env.DEPS }}
          key: ${{ matrix.os }}-${{ env.CC }}-${{ hashFiles('**/common.env') }}-v${{ env.CACHE_VER }}

      - name: Cache check
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "Failed to upload cache"
          false

      - name: Checkout shell test framework
        uses: actions/checkout@v3
        with:
          repository: kward/shunit2
          path: ${{github.workspace}}/tests/shunit2
          fetch-depth: 1

      - name: Run tebako tests (set no. 1)
        run:  |
          bundle install
          RUBY_VER=${{ matrix.package_ruby_ver }} ${{github.workspace}}/tests/scripts/functional-tests.sh

      - name: Upload tebako test packages
        if: ${{ matrix.package_ruby_ver == env.RUBY_VER && matrix.env.CC == 'clang' }}
        uses: actions/upload-artifact@v3
        with:
          name: test-packages
          retention-days: 1
          path: |
            test-01-package
            test-11-package
            test-15-package
            test-18-package
            test-19-package

  tests-2:
    needs: setup
    name: tests-2 ${{ matrix.os }} Ruby ${{ matrix.package_ruby_ver }} CC ${{ matrix.env.CC }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-20.04 ]
        package_ruby_ver: [ '2.7.7', '3.0.6', '3.1.4' ]
        env:
          - CC: gcc
            CXX: g++
          - CC: clang
            CXX: clang++
    env: ${{ matrix.env }}
    steps:
      - name: Checkout tebako packaging environment
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          submodules: true

      - name: Setup environment
        run: cat common.env >> $GITHUB_ENV

      - name: Switch to gcc-9
        if: ${{ matrix.env.CC == 'gcc' }}
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 100 --slave /usr/bin/g++ g++ /usr/bin/g++-9 --slave /usr/bin/gcov gcov /usr/bin/gcov-9
          sudo update-alternatives --set gcc /usr/bin/gcc-9

      - name: Install packages
        run: |
          sudo apt-get -y update
          sudo apt-get -y install \
          binutils-dev libevent-dev acl-dev libfmt-dev libjemalloc-dev \
          libdouble-conversion-dev libiberty-dev liblz4-dev liblzma-dev libssl-dev \
          libboost-context-dev libboost-filesystem-dev libboost-program-options-dev \
          libboost-regex-dev libboost-system-dev libboost-thread-dev \
          libunwind-dev libdwarf-dev libelf-dev libgoogle-glog-dev \
          libffi-dev libgdbm-dev libyaml-dev libncurses-dev libreadline-dev \
          libsqlite3-dev

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY_VER }}
          bundler: ${{ env.BUNDLER_VER }}
          bundler-cache: false

      - name: Create deps folder
        run: mkdir ${{ github.workspace }}/${{ env.DEPS }}

      - name: Process cache
        id: cache
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/${{ env.DEPS }}
          key: ${{ matrix.os }}-${{ env.CC }}-${{ hashFiles('**/common.env') }}-v${{ env.CACHE_VER }}

      - name: Cache check
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          echo "Failed to upload cache"
          false

      - name: Run tebako tests (set no. 2)
        run: |
          bundle install
          RUBY_VER=${{ matrix.package_ruby_ver }} ruby ${{github.workspace}}/tests-2/tebako-test.rb

#  test-on-ubuntu-latest:
#    needs: tests-1
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout tebako packaging environment
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 1
#
#      - name: Download test packages
#        uses: actions/download-artifact@v3
#        with:
#          name: test-packages
#
#      - name: Run test packages
#        run:  tests/scripts/cross-tests.sh
